/**
 * JS-доступ к design tokens (Leaflet, print HTML, manifest, canvas).
 * Значения синхронизированы с tokens.css — при изменении обновляйте оба файла.
 */
export const tokens = {
  colors: {
    brand: '#ff9800',
    brandLight: '#fdb913',
    brandDark: '#f57c00',
    primary: '#ff9800',
    primaryHover: '#f57c00',
    primaryLight: '#fdb913',
    primarySoft: '#ffb74d',
    primarySoftHover: '#ffcc80',
    primaryEmphasis: '#c2410c',
    primarySurface: '#fff4e5',
    textPrimary: '#111827',
    textSecondary: '#374151',
    textMuted: '#5c5c6b',
    textDisabled: '#9ca3af',
    textOnBrand: '#ffffff',
    bgBase: '#ffffff',
    bgSurface: '#ffffff',
    bgSubtle: '#f3f4f6',
    bgInput: '#f3f3f5',
    bgContact: '#fafafa',
    bgLandingDark: '#15120f',
    borderStrong: '#eef0f3',
    placeholderBg: '#f3f4f6',
    placeholderShape: '#d1d5db',
    danger: '#d4183d',
    success: '#16a34a',
    warning: '#f59e0b',
    info: '#0284c7',
    telegram: '#0088cc',
    telegramHover: '#006699',
    telegramBright: '#229ed9',
    telegramBrightHover: '#1e8bc3',
    viber: '#7360f2',
    viberHover: '#5a4dd4',
    viberAlt: '#625ba1',
    viberAltHover: '#514da1',
    mapPin: '#2563eb',
  },
  typography: {
    fontFamily: "'Inter', system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
    fontFamilyDisplay: "'Manrope', 'Inter', system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif",
    textXs: '12px',
    textSm: '14px',
    textMd: '16px',
    textLg: '18px',
    textXl: '20px',
    text2xl: '24px',
    text3xl: '30px',
    text4xl: '36px',
    fontWeightRegular: 400,
    fontWeightMedium: 500,
    fontWeightSemibold: 600,
    leadingTight: 1.25,
    leadingNormal: 1.5,
    leadingRelaxed: 1.75,
    trackingHeading: '-0.01em',
  },
  spacing: {
    1: '4px',
    2: '8px',
    3: '12px',
    4: '16px',
    5: '20px',
    6: '24px',
    8: '32px',
    10: '40px',
    12: '48px',
    16: '64px',
    20: '80px',
    24: '96px',
    contentMax: '1200px',
    contentMaxMedium: '1024px',
    contentMaxNarrow: '896px',
    contentMaxReadable: '768px',
    sectionGap: '24px',
  },
  radius: {
    sm: '3px',
    md: '6px',
    lg: '8px',
    xl: '10px',
    '2xl': '12px',
    '3xl': '14px',
    full: '9999px',
  },
  shadow: {
    xs: '0 1px 2px rgba(0,0,0,0.05)',
    sm: '0 1px 3px rgba(0,0,0,0.08), 0 1px 2px rgba(0,0,0,0.04)',
    md: '0 4px 8px rgba(0,0,0,0.08), 0 2px 4px rgba(0,0,0,0.04)',
    lg: '0 12px 24px rgba(0,0,0,0.08), 0 4px 8px rgba(0,0,0,0.04)',
    printSheet: '0 8px 40px rgba(0,0,0,0.08)',
    mapCluster: '0 2px 10px rgba(0,0,0,0.28)',
  },
  transition: {
    fast: '100ms',
    base: '150ms',
    slow: '250ms',
    ease: 'cubic-bezier(0.16, 1, 0.3, 1)',
    interactive: '150ms cubic-bezier(0.16, 1, 0.3, 1)',
  },
  scenario: {
    lost: '#e11d48',
    lostSoft: '#fff1f2',
    lostBorder: '#fecdd3',
    lostForeground: '#881337',
    found: '#0284c7',
    foundSoft: '#f0f9ff',
    foundBorder: '#bae6fd',
    foundForeground: '#0c4a6e',
    shelter: '#059669',
    shelterSoft: '#ecfdf5',
    shelterBorder: '#a7f3d0',
    shelterForeground: '#065f46',
  },
  /* Латунь адресника/жетона — регистр «забота и порядок» (без сценарной тревожности) */
  medallion: {
    base: '#b98a2f',
    soft: '#faf6ec',
    border: '#e7d9b8',
    foreground: '#7a5b1e',
  },
  map: {
    searching: '#e11d48',
    found: '#0284c7',
    spotted: '#f97316',
    fostering: '#a855f7',
    shelter: '#059669',
    returned: '#10b981',
    adopted: '#059669',
    transferred: '#14b8a6',
    fallback: '#6b7280',
    sighting: '#f59e0b',
    flyerFound: '#0284c7',
    flyerFoundSoft: '#f0f9ff',
    flyerFoundBorder: '#bae6fd',
    flyerLost: '#e11d48',
    flyerLostSoft: '#fff1f2',
    flyerLostBorder: '#fecdd3',
  },
} as const;

/** CSS var references for runtime (inline styles, SVG, print HTML). */
export const cssVar = {
  brand: 'var(--color-brand)',
  primary: 'var(--color-primary)',
  primaryHover: 'var(--color-primary-hover)',
  primaryLight: 'var(--color-primary-light)',
  primarySoftHover: 'var(--color-primary-soft-hover)',
  primarySurface: 'var(--color-primary-surface)',
  textPrimary: 'var(--color-text-primary)',
  textSecondary: 'var(--color-text-secondary)',
  textMuted: 'var(--color-text-muted)',
  textDisabled: 'var(--color-text-disabled)',
  bgBase: 'var(--color-bg-base)',
  bgSurface: 'var(--color-bg-surface)',
  bgSubtle: 'var(--color-bg-subtle)',
  bgInput: 'var(--color-bg-input)',
  bgContact: 'var(--color-bg-contact)',
  borderDefault: 'var(--color-border-default)',
  borderStrong: 'var(--color-border-strong)',
  borderFocus: 'var(--color-border-focus)',
  success: 'var(--color-success)',
  warning: 'var(--color-warning)',
  danger: 'var(--color-danger)',
  info: 'var(--color-info)',
  telegram: 'var(--color-telegram)',
  telegramHover: 'var(--color-telegram-hover)',
  telegramBright: 'var(--color-telegram-bright)',
  viber: 'var(--color-viber)',
  viberAlt: 'var(--color-viber-alt)',
  mutedForeground: 'var(--muted-foreground)',
  border: 'var(--border)',
  card: 'var(--card)',
  background: 'var(--background)',
  foreground: 'var(--foreground)',
  muted: 'var(--muted)',
  inputBackground: 'var(--input-background)',
  sliderTrack: 'var(--color-slider-track)',
  ring: 'var(--ring)',
} as const;

export type DesignTokens = typeof tokens;
